FROM ruby:2.4
MAINTAINER Rich Daley <rich@fishpercolator.co.uk>
ENV REFRESHED_AT <%= Date.today.to_s %>

RUN adduser --uid <%= Process.uid %> --disabled-password --gecos "" rails

RUN gem install bundler

ENV APP_HOME /usr/src/<%= appname %>
RUN mkdir $APP_HOME
WORKDIR $APP_HOME
ADD Gemfile* $APP_HOME/

ENV BUNDLE_GEMFILE=$APP_HOME/Gemfile BUNDLE_JOBS=2 BUNDLE_PATH=/bundle

RUN bundle install

ENV RAILS_ENV       production
ENV DOMAIN_NAME     localhost
# NOTE: ALWAYS override this or your sessions will be insecure!
ENV SECRET_KEY_BASE <%= SecureRandom.hex(64) %>

ADD . $APP_HOME

RUN RAILS_ENV=production bundle exec rake assets:precompile

CMD ["bundle", "exec", "puma", "-C", "config/puma.rb"]
